# Generated by Django 5.0.8 on 2024-10-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(db_column='IDResto', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NomResto', max_length=255)),
                ('ville', models.CharField(db_column='Ville', max_length=255)),
            ],
            options={
                'db_table': 'Restaurant',
                'managed': False,
            },
        ),
    ]
